### ISSUE TITLE
Result different during inference 

### ISSUE THREAD

**Issue by y556zhao** [NVlabs/contact_graspnet#13]
Hi,

I was using default parameters to test the model on 7.npy, and the resulting grasps are sparse as shown in the image below. May I ask if I was doing anything wrong? 

Here is the command I used: python contact_graspnet/inference.py  --np_path=test_data/7.npy  --local_regions --filter_grasps

Checkpoint: checkpoints/scene_test_2048_bs3_hor_sigma_001

Thank you!
@MartinSmeyer 
![grasp](https://user-images.githubusercontent.com/43657501/148443274-9796b842-ed98-411a-9bce-87e7569dd3a4.JPG)

**Comment by MartinSmeyer** [comment]
Hi,

This looks like issue #9 

Apparently, users of newer GPUs require tensorflow-gpu=2.5 with CUDA >= 11 to run this code. Recompile the tf_ops if you use a newer version. Does this help?

I will update the requirements soon.

Best,

Martin

**Comment by y556zhao** [comment]
Yes, it works! Thank you so much for helping!
