### ISSUE TITLE
conflict environment

### ISSUE THREAD

**Issue by xlim1996** [NVlabs/contact_graspnet#19]
Hi,
My GPU is GTX3080Ti and i try to use contact_graspnet(inferency.py).it's pretty slow. I have seen the other issues #16 and #9. I try to use cuda11.2 and cudnn8.1 with TensorFlow-gpu2.5. But it exits a lot of packages conflict and python package bugs.
So, is it possible that you provide a new version yml file for  TensorFlow-gpu2.5?

Best regards,
xiaolin

**Comment by MartinSmeyer** [comment]
Hi,
Yes, several people seem to have issues with that. I will provide a new environment next week when I am back to Germany. 
Best,
Martin

**Comment by xlim1996** [comment]
Thank you in advance.  It will be very helpful.

**Comment by xlim1996** [comment]
@MartinSmeyer
Hi Martin,
I want to know where you provide the new environment file? Because I don't know where I can find the new environment file. 

best,
xiaolin

**Comment by MartinSmeyer** [comment]
Currently have some more urgent things to do but hope to find some time this weekend. If this is too late for you, give it a shot yourself, it shouldn't be too hard.

**Comment by AmanuelErgogo** [comment]
@xlim1996 
Hi, have you solve this issue and could you share environment file?

**Comment by xlim1996** [comment]
@AmanuelErgogo  
Hi,i send you the link. you can download it.
https://drive.google.com/file/d/1_02uAnqkAR-PZmo1Dku5pW-AUHAz5aiG/view?usp=sharing
If it don't work,you can try the following code:
`conda create --name contact_graspnet python=3.8
conda activate contact_graspnet
conda install -c conda-forge cudatoolkit=11.2(or 11.3)
conda install -c conda-forge cudnn=8.2
pip install tensorflow==2.5 tensorflow-gpu=2.5
pip install opencv-python-headless
pip install pyyaml
pip install pyrender
pip install tqdm
pip install mayavi`

After you have successfully create a env, don't forget to recompile pointnet2 tf_ops: 
`sh compile_pointnet_tfops.sh`
I hope it can help you.

Best regards,
xiaolin

**Comment by AmanuelErgogo** [comment]
Thanks @xlim1996 
it works with the environment setup you shared on Ubuntu 20.04 with Nvidia A5000 after changing pyyaml version from 6.0 to 5.4.1.

**Comment by MartinSmeyer** [comment]
Thank you guys!

**Comment by HanzhiC** [comment]
> @AmanuelErgogo Hi,i send you the link. you can download it. https://drive.google.com/file/d/1_02uAnqkAR-PZmo1Dku5pW-AUHAz5aiG/view?usp=sharing If it don't work,you can try the following code: `conda create --name contact_graspnet python=3.8` `conda activate contact_graspnet` `conda install -c conda-forge cudatoolkit=11.2(or 11.3)` `conda install -c conda-forge cudnn=8.2` `pip install tensorflow==2.5 tensorflow-gpu=2.5` `pip install opencv-python-headless` `pip install pyyaml` `pip install pyrender` `pip install tqdm` `pip install mayavi`
> 
> After you have successfully create a env, don't forget to recompile pointnet2 tf_ops: `sh compile_pointnet_tfops.sh` I hope it can help you.
> 
> Best regards, xiaolin

can you share the env.yaml again? thanks!

**Comment by a-badithela** [comment]
can you upload a new yaml file? the link was die @@

**Comment by andyoung009** [comment]
Would you please share the env.yaml again? the shared file is gone. thanks!

**Comment by ekjt** [comment]
I have been struggling with the same issues. GPU: 3090, CUDA: 11.3, Ubuntu: 20.04 . I was able to get their demos working with the following setup:

```
#build env
conda create --name contact_graspnet python=3.8
conda activate contact_graspnet
conda install -c conda-forge cudatoolkit=11.2
conda install -c conda-forge cudnn=8.2
pip install tensorflow==2.5 tensorflow-gpu==2.5
pip install opencv-python-headless
pip install pyyaml==5.4.1
pip install pyrender
pip install tqdm
pip install configobj
conda install mayavi=4.7.1
conda install matplotlib=3.3.2
pip install numpy==1.23.4

#compile pointnet
 sh compile_pointnet_tfops.sh

#run demo
 python contact_graspnet/inference.py \
       --np_path=test_data/*.npy \
       --local_regions --filter_grasps
```

**Comment by bkolligs** [comment]
Hey @ekjt, it doesn't seem like `mayavi==4.7.1` works with Python 3.8. How did you get that environment to work? 

EDIT: I needed to use the `conda-forge` channel, as:
```
#build env
conda create --name contact_graspnet python=3.8
conda activate contact_graspnet
conda install -c conda-forge cudatoolkit=11.2
conda install -c conda-forge cudnn=8.2
pip install tensorflow==2.5 tensorflow-gpu==2.5
pip install opencv-python-headless
pip install pyyaml==5.4.1
pip install pyrender
pip install tqdm
pip install configobj
conda install -c conda-forge mayavi=4.7.1
conda install matplotlib=3.3.2
pip install numpy==1.23.4

#compile pointnet
sh compile_pointnet_tfops.sh

#run demo
python contact_graspnet/inference.py \
       --np_path=test_data/*.npy \
       --local_regions --filter_grasps
```
