### ISSUE TITLE
Normalizing depth image for inference 

### ISSUE THREAD

**Issue by AmanuelErgogo** [NVlabs/contact_graspnet#24]
Hi, @MartinSmeyer 

I wanted to test the inference.py on real-time data from realsense depth camera. and I realized depth image from the provided test data is normalized while the depth image from realsense camera is uint16 format.
I tried to normalize using this formula but i am not certain about the range.
 `depth_normalized = (depth - min_depth) / (max_depth - min_depth)`
so, could you provide the range used to normalize or any other ways to preprocess depth image?

Thanks,
Amanuel

**Comment by MartinSmeyer** [comment]
Hi @AmanuelErgogo,

You don't need to normalize the depth, in fact it should be just in meters. If you know your workspace, it is beneficial to pass a suitable `--z_range=[0.2,1.1]` which cuts off foreground/background measurements.
