### ISSUE TITLE
Fingers length

### ISSUE THREAD

**Issue by BryanBetancur** [NVlabs/contact_graspnet#25]
Hello, Thank you for your awesome code. 
I'm trying to implement your code with a different gripper, the fingers are longer but I haven't been able to find where to adjust this.
Could you help me, please?

**Comment by MartinSmeyer** [comment]
Hey @BryanBetancur,

There is a parameter in the test config called `center_to_tip`:
https://github.com/NVlabs/contact_graspnet/blob/f28013a1a9f593fafc7c6dc0ca022b63464800a0/contact_graspnet/config.yaml#L181

Set it to the additional finger length * 2 in meters. :)

**Comment by BryanBetancurUR** [comment]
It works. Thank you very much for your answer. :)

**Comment by BryanBetancur** [comment]
It works. Thank you very much. c:
