### ISSUE TITLE
adapt the constant distance from the gripper baseline to the gripper base

### ISSUE THREAD

**Issue by xlim1996** [NVlabs/contact_graspnet#26]
Hello,@MartinSmeyer
I'm trying to adapt the constant distance from the gripper baseline to the gripper base because I'm using a different gripper. The constant distance from the gripper baseline to the gripper base is shorter, but I haven't been able to find where to adjust this.
Could you help me, please?

**Comment by Imhpy** [comment]
> Hello,[@MartinSmeyer](https://github.com/MartinSmeyer) I'm trying to adapt the constant distance from the gripper baseline to the gripper base because I'm using a different gripper. The constant distance from the gripper baseline to the gripper base is shorter, but I haven't been able to find where to adjust this. Could you help me, please?

Hello, I'm encountering the same problem as you. Have you solved it?
