### ISSUE TITLE
Scores model output

### ISSUE THREAD

**Issue by danialdunson** [NVlabs/contact_graspnet#27]
I have noticed that the model produces scores when segmentation mask is set to None. Do these scores have any significance and if so what is that? 

P.S.
I added your model as a servicecall in a ROSBRIDGE, and, currently, I am naively selecting the top 5 poses with the highest `score` values without a segmentation mask.
Also, i added the the appropriate transforms to get it working on the interbotix wx250s. its surprisingly good even before training and just filtering out invalid gripper widths. I am a senior in undergrad btw, so my journey has been similar to: https://github.com/NVlabs/contact_graspnet/issues/8

**Comment by MartinSmeyer** [comment]
Hey @danialdunson,

sorry, missed your issue over the summer somehow. If you do not provide a segmentation mask the network will not focus on a particular object but predict grasps for the entire scene. It's even better though if it can focus as described [here](https://github.com/NVlabs/contact_graspnet#inference).
