### ISSUE TITLE
Gripper Width 

### ISSUE THREAD

**Issue by BryanBetancur** [NVlabs/contact_graspnet#28]
Hello, Thank you again for your code.
I tried to change gripper width in config file but I didn't see any difference in inference. I need to train again to change this feature? also I saw the filter with the gripper oppenings but I didn't find a consistent relation, could you explain me it, please.

**Comment by MartinSmeyer** [comment]
Hey @BryanBetancur,
The model is trained using physics simulations of the pandas gripper so it's not simply a parameter that you can change. You can hack the model to work with other gripper widths or retrain the model as described in #8.

**Comment by BryanBetancurUR** [comment]
Okay, thanks for your time. :D

**Comment by BryanBetancur** [comment]
Okay, thanks for your time. :D
