### ISSUE TITLE
Issue fo using my own data 

### ISSUE THREAD

**Issue by henry890112** [NVlabs/contact_graspnet#31]
Hello, I am using my own data to train contact graspnet. However, I am unable to obtain thicker grasping poses in the output. Could this be due to a problem with my data or do I need to modify the test_data/*.npy files? I have attached my input and output data for reference. Thank you!

![Screenshot from 2023-02-14 17-01-42](https://user-images.githubusercontent.com/105191477/218688393-697d1676-c2e1-44bb-93de-d8100dda52be.png)

![Screenshot from 2023-02-14 17-03-33](https://user-images.githubusercontent.com/105191477/218688923-81718d4b-18a7-408a-a6e9-81e516b5d779.png)

![Screenshot from 2023-02-14 16-54-49](https://user-images.githubusercontent.com/105191477/218686863-6c064b78-245c-46b7-90e9-e5d860b625f4.png)

![Screenshot from 2023-02-14 16-55-06](https://user-images.githubusercontent.com/105191477/218689165-2570682e-b1aa-49ad-a54f-395620279ff9.png)

**Comment by MartinSmeyer** [comment]
Hey @henry890112,

What robot / gripper model do you use? If your gripper width is wider than the 8cm of the Franka Panda Gripper, than check #28

**Comment by henry890112** [comment]
I apologize for the poor description of my issue, but my question is: I am unable to achieve the grasping pose that is highlighted in green, just like which I have attached below. Thank you for your patience.
![image](https://user-images.githubusercontent.com/105191477/218734996-9281c4b4-ff76-4808-aabd-fb4700a16430.png)

**Comment by MartinSmeyer** [comment]
Sorry still unclear, that is not a question

**Comment by MartinSmeyer** [comment]
Yes this is the highest scoring grasp pose. Ah ok, it's just about the visualization, the most confident grasps are only shown if you have more than one object in your mask image: 

https://github.com/NVlabs/contact_graspnet/blob/a12b7e3a1d7adf38762bfae1c8b84b4550059a6f/contact_graspnet/visualization_utils.py#L99-L105

**Comment by henry890112** [comment]
Thank for your answer!

**Comment by Haitham-Yaghi** [comment]
What command did you use to run inference on the above data?
