### ISSUE TITLE
cannot obtain a strong and accurate grasp net

### ISSUE THREAD

**Issue by a-badithela** [NVlabs/contact_graspnet#37]
I followed all of the instructions step by step, but my grip map looks terrible, even after running the sample file:
![ppppp](https://github.com/NVlabs/contact_graspnet/assets/108789351/81e9efe3-8ea3-4cc5-995a-efaeb8878986)

![pppppp](https://github.com/NVlabs/contact_graspnet/assets/108789351/3182a647-a2e7-462d-86c1-f478ae805a61)

So here's the image I already generate the segmentation mask, but my grasp net was bad: 
![xxxx](https://github.com/NVlabs/contact_graspnet/assets/108789351/18cd529f-df7e-43c8-b1f3-c037f064ec5f)

![xxxxxxxxxxxxxx](https://github.com/NVlabs/contact_graspnet/assets/108789351/ea7ad930-e8dd-4026-8cf7-973ee71c9317)

any ideas I can fix that, please?

**Comment by andyoung009** [comment]
Hi, I am also interested in this work, did your slove this problem? Thank you!
