### ISSUE TITLE
tf_sampling_so.so: undefined symbol: _ZN10tensorflow14kernel_factory17OpKernel

### ISSUE THREAD

**Issue by ChengYaofeng** [NVlabs/contact_graspnet#4]
tensorflow.python.framework.errors_impl.NotFoundError: /home/cyf/contact_graspnet/pointnet2/tf_ops/sampling/tf_sampling_so.so: **undefined symbol: _ZN10tensorflow14kernel_factory17OpKernel**Registrar12InitInternalEPKNS_9KernelDefEN4absl11string_viewESt10unique_ptrINS0_15OpKernelFactoryESt14default_deleteIS8_EE

I found that it is because the g++ version > 4, maybe some other problem. So how can I solve it ?

**Comment by ChengYaofeng** [comment]
> tensorflow.python.framework.errors_impl.NotFoundError: /home/cyf/contact_graspnet/pointnet2/tf_ops/sampling/tf_sampling_so.so: **undefined symbol: _ZN10tensorflow14kernel_factory17OpKernel**Registrar12InitInternalEPKNS_9KernelDefEN4absl11string_viewESt10unique_ptrINS0_15OpKernelFactoryESt14default_deleteIS8_EE
> 
> I found that it is because the g++ version > 4, maybe some other problem. So how can I solve it ?

**Comment by ChengYaofeng** [comment]
OK，I solved it!

**Comment by alemon-cherry** [comment]
Could you please share how did you solve this problem?

**Comment by heartInsert** [comment]
So , how  do  you  solve  this  problem?

**Comment by ChengYaofeng** [comment]
> So , how do you solve this problem?

Sorry, it's been a long time, and I can't remember what I've done. It seems I had changed the g++ version of the virtual environment. If you want to try ContactGraspNet's PyTorch version, you can find the repo on my [GitHub](https://github.com/ChengYaofeng/PCF-Grasp/blob/o3dvis/pcfgrasp/model/cgnet.py).
